### ISSUE TITLE
Не переходит на следующий том

### ISSUE THREAD

**Issue by keuue** [JumpJets/Archive-ranobelib-userscript#1]
Здравствуйте, заметил несколько проблем. В html версии не переходит на следующий том после последней главы предыдущего. Например, первый том заканчивается на 21 главе(v1_021), затем при нажатии на кнопку оно переходит на 22 главу этого же тома(v1_022), а должен перейти на 22 главу следующего(v2_022). Кроме этого, игнорируются половинчатые или неполные главы, то бишь 1.1, 1.2, 1.5 и т.д. И еще если счет глав идет заново с нового тома, то тоже не переключается на новую главу.

**Comment by XCanG** [comment]
Да, там был очень тупой скрипт, я из строки просто добавил счётчик, надо было быстро накатать скрипт для друга поэтому не запаривался с этим косяком.

https://github.com/JumpJets/Archive-ranobelib-userscript/blob/ccdb47856d1f30968d89d977763fa7d8ad9e2598/Archive%20ranobe.user.js#L86-L87

Из JS нельзя смотреть файлы в файловой системе, поэтому я сделал такой костыль вслепую.

Про неполные главы не видел, скинь ссылку на страницу с неполными главами.

**Comment by XCanG** [comment]
@Lafrend обновил userscript, добавил меню и исправил навигацию. Думаю понравится.

Главы 1.5 и им подобные тоже должны нормально сейчас забираться, проверил на https://ranobelib.me/demony-voiny?section=chapters

**Comment by keuue** [comment]
Огосподи это теперь точно нужно, теперь всё прекрасно работает. Ты просто лучший!
Огромное тебе спасибо)

**Comment by XCanG** [comment]
Я ещё покопался с мангой и там тоже не так сложно вытащить картинки, хотя там есть две проблемы: с разделением глав на несколько переводчиков (тут надо что-то придумать для шаблона) и не всегда сервер отвечает добром на картинку (там конечно есть зеркала но невозможность скачать с одного всё усложняет в 2 раза).

Может быть завтра допилю.

**Comment by keuue** [comment]
А ты хочешь для манги тоже сделать читалку(как с ранобэ) или просто скачивание всех глав?

**Comment by XCanG** [comment]
Скачивание уже есть если не считать проблему с сервером. Там основная проблема только лимит ОЗУ на вкладку ибо всё в кеше хранится пока качаешь.

Там с форматом глав беда ибо где несколько команд, там есть несколько одинаковых глав, типо том 1 глава 1, но переводчик А и переводчик Б.

А это значит что сохранять надо не по типу `/vol_chapter/page.png` а по типу `/team/vol_chapter/page.png`
Ну и в html отсеивать результаты ещё.

**Comment by keuue** [comment]
А может лучше просто сделать выбор от какой команды скачивать перевод?

**Comment by keuue** [comment]
Так и меньше кеша будет занято, и времени на скачку меньше(это всё ж таки картинки, а не текст)

**Comment by XCanG** [comment]
> А может лучше просто сделать выбор от какой команды скачивать перевод?

Тут проблема в том что бывает часть глав (начальные) от 1 команды, затем другая подхватила и продолжает.
Если сохранять по отдельности то не будет целостности, а html руками никто править не будет (тем более если не знают).

**Comment by XCanG** [comment]
Залил userscript для мангалиба и хентайлиба, пока начальную версию с базовым функционалом

* https://github.com/JumpJets/Archive-mangalib-userscript
